######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 23 22:59:28 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += plot.hh sdrgui.hh start.xpm ../libsig/cpp_monit.hh
SOURCES += main.cc plot.cc sdrgui.cc
