######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 23 22:59:28 2009
######################################################################

TEMPLATE = app
TARGET = test
DEPENDPATH += .
INCLUDEPATH += .

QWT_VERSION      =5.1.1
QWT_DIR = /usr/local/qwt-$$QWT_VERSION 

LIBS += -L$$QWT_DIR/lib -lqwt
INCLUDEPATH += $$QWT_DIR/include

# Input
HEADERS += plot.hh sdrgui.hh start.xpm 
SOURCES += main.cc plot.cc sdrgui.cc
