#include "sig_blas.hh"
#include <emmintrin.h>
#include <math.h>

float   sdot_cpp(int n, float  *x,float  *y) { float  s=0.0;    while (n--)     { s+=*(x++) * *(y++); }; return s; }

float  sdot_sse(int   nv, float  *xv, float  *yv)
{ 

  float res; res = 0.0f;

  __asm__ __volatile__ (							
		    "            xorps     %%xmm7, %%xmm7                             \n "
		    "            mov       %%ecx,%%edx    /* %%ecx = %%edx = n/4 */   \n "
		    "            movaps    %%xmm7,%%xmm0                              \n "
		    "            movaps    %%xmm7,%%xmm1                              \n "
		    "            movaps    %%xmm7,%%xmm2                              \n "
		    "            movaps    %%xmm7,%%xmm3                              \n "
		    "            movaps    %%xmm7,%%xmm4                              \n "
		    "            movaps    %%xmm7,%%xmm5                              \n "
		    "            movaps    %%xmm7,%%xmm6                              \n "
		    "            shrl       $2,%%edx                                  \n "
		    "            andl       $0x07,%%edx                               \n "
		    "            je        kk1%=                                      \n "
		    "            movaps    (%%eax),%%xmm6                             \n "
		    "            mulps     (%%ebx),%%xmm6                             \n "
		    "            cmp       $3,%%edx                                   \n "
		    "            jg        kkg3%=                                     \n "
		    "            jne       kkg9%=                                     \n "
		    "            movaps    0x10(%%eax),%%xmm5                         \n "
		    "            mulps     0x10(%%ebx),%%xmm5                         \n "
		    "            movaps    0x20(%%eax),%%xmm4                         \n "
		    "            mulps     0x20(%%ebx),%%xmm4                         \n "
		    "            jmp       kk0%=                                      \n "
		    " kkg9%=:  cmp       $2,%%edx                                     \n "
		    "            jl        kk0%=                                      \n "
		    "            movaps    0x10(%%eax),%%xmm5                         \n "
		    "            mulps     0x10(%%ebx),%%xmm5                         \n "
		    "            jmp       kk0%=                                      \n "
		    " kkg3%=: movaps    0x30(%%eax),%%xmm3                            \n "
		    "            movaps    0x20(%%eax),%%xmm4                         \n "
		    "            mulps     0x30(%%ebx),%%xmm3                         \n "
		    "            movaps    0x10(%%eax),%%xmm5                         \n "
		    "            mulps     0x20(%%ebx),%%xmm4                         \n "
		    "            mulps     0x10(%%ebx),%%xmm5                         \n "
		    "            cmp       $5,%%edx                                   \n "
		    "            jg        kkg5%=                                     \n "
		    "            jne       kk0%=                                      \n "
		    "            movaps    0x40(%%eax),%%xmm2                         \n "
		    "            mulps     0x40(%%ebx),%%xmm2                         \n "
		    "            jmp       kk0%=                                      \n "
		    " kkg5%=: movaps    0x50(%%eax),%%xmm1                            \n "
		    "            mulps     0x50(%%ebx),%%xmm1                         \n "
		    "            movaps    0x40(%%eax),%%xmm2                         \n "
		    "            mulps     0x40(%%ebx),%%xmm2                         \n "
		    "            addps     %%xmm1,%%xmm3                              \n "
		    "            cmp       $6,%%edx                                   \n "
		    "            je        kk0%=                                      \n "
		    "            movaps    0x60(%%eax),%%xmm0                         \n "
		    "            mulps     0x60(%%ebx),%%xmm0                         \n "
		    "            addps     %%xmm0,%%xmm2                              \n "
		    " kk0%=:  shll       $4,%%edx                                     \n "
		    "            addl       %%edx,%%ebx                               \n "
		    "            addl       %%edx,%%eax                               \n "
		    " kk1%=:  mov       %%ecx,%%edx                                   \n "
		    "            shrl       $5,%%ecx                                  \n "
		    "            je        kmp3%=                                     \n "
		    "            movaps    (%%eax),%%xmm0                             \n "
		    "            movaps    0x10(%%eax),%%xmm1                         \n "
		    " .p2align 4    /* each loop does 32 add+multiply */              \n "
		    " kmp2%=: mulps     (%%ebx),%%xmm0                                \n "
		    "            addps     %%xmm2,%%xmm6                              \n "
		    "            movaps    0x20(%%eax),%%xmm2                         \n "
		    "            mulps     0x10(%%ebx),%%xmm1                         \n "
		    "            addps     %%xmm3,%%xmm7                              \n "
		    "            movaps    0x30(%%eax),%%xmm3                         \n "
		    "            mulps     0x20(%%ebx),%%xmm2                         \n "
		    "            addps     %%xmm0,%%xmm4                              \n "
		    "            movaps    0x40(%%eax),%%xmm0                         \n "
		    "            mulps     0x30(%%ebx),%%xmm3                         \n "
		    "            addps     %%xmm1,%%xmm5                              \n "
		    "            movaps    0x50(%%eax),%%xmm1                         \n "
		    "            mulps     0x40(%%ebx),%%xmm0                         \n "
		    "            addps     %%xmm2,%%xmm6                              \n "
		    "            movaps    0x60(%%eax),%%xmm2                         \n "
		    "            mulps     0x50(%%ebx),%%xmm1                         \n "
		    "            addps     %%xmm3,%%xmm7                              \n "
		    "            movaps    0x70(%%eax),%%xmm3                         \n "
		    "            mulps     0x60(%%ebx),%%xmm2                         \n "
		    "            addps     %%xmm0,%%xmm4                              \n "
		    "            movaps    0x80(%%eax),%%xmm0                         \n "
		    "            mulps     0x70(%%ebx),%%xmm3                         \n "
		    "            addps     %%xmm1,%%xmm5                              \n "
		    "            movaps    0x90(%%eax),%%xmm1                         \n "
		    "            add	   $0x80,%%ebx                                \n "
		    "            add	   $0x80,%%eax                                \n "
		    "            dec	   %%ecx                                      \n "
		    "            jne	   kmp2%=                                     \n "
		    " kmp3%=: addps     %%xmm2,%%xmm6                                 \n "
		    "            addps     %%xmm3,%%xmm7                              \n "
		    "            addps     %%xmm5,%%xmm4                              \n "
		    "            addps     %%xmm6,%%xmm7                              \n "
		    "            addps     %%xmm7,%%xmm4                              \n "
		    "            xorps     %%xmm0,%%xmm0                              \n "
		    "            movhlps   %%xmm4,%%xmm0                              \n "
		    "            addps     %%xmm4,%%xmm0                              \n "
		    "            movaps    %%xmm0,%%xmm1                              \n "
		    "            shufps    $0xE1,%%xmm4,%%xmm1                        \n "
		    "            addss     %%xmm1, %%xmm0                             \n "
		    "            andl      $3,%%edx                                   \n "
		    "            je       kmp4%=                                      \n "
		    "            movss    (%%eax),%%xmm1                              \n "
		    "            mulss    (%%ebx),%%xmm1                              \n "
		    "            addss    %%xmm1,%%xmm0                               \n "
		    "            dec      %%edx                                       \n "
		    "            je       kmp4%=                                      \n "
		    "            movss    4(%%eax),%%xmm2                             \n "
		    "            mulss    4(%%ebx),%%xmm2                             \n "
		    "            addss    %%xmm2,%%xmm0                               \n "
		    "            dec      %%edx                                       \n "
		    "            je       kmp4%=                                      \n "
		    "            movss    8(%%eax),%%xmm3                             \n "
		    "            mulss    8(%%ebx),%%xmm3                             \n "
		    "            addss    %%xmm3,%%xmm0                               \n "
		    " kmp4%=: movss    %%xmm0, (%0)                                   \n "
		    : 
		    : "S" (&res),"c" (nv), "a" (xv), "b" (yv)                 
		    : "%edx", "memory" 
									);
  return res;
}
