######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 2 11:52:12 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lusrp -lfftw3

# Input
HEADERS += scope.h usrpiface.h
SOURCES += main.cpp scope.cpp usrpiface.cpp
